import * as memory from "./memory"
import * as sb from "./supabase"
import { supabaseConfigured } from "./supabase"
import type {
  ContainmentActionRecord,
  Department,
  Event,
  Honeytoken,
  Incident,
  SecurityLevel,
} from "../types"

/**
 * Storage facade.
 *
 * Two backends behind one async contract:
 *
 *   Supabase — used when SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.
 *   In-memory — used otherwise, and as a fallback if a Supabase call throws.
 *
 * Serverless is what forces this. On Vercel each route runs in its own
 * container with its own `globalThis`, so a decoy generated by one request is
 * invisible to the next — which is why decoy share links appeared to break in
 * production while working locally. Shared state has to live outside the
 * process.
 *
 * Every function here is async even on the memory path, so the two backends are
 * interchangeable and callers never branch on which one is live.
 *
 * The fallback is deliberate and mirrors the AI layer: a network problem must
 * degrade the demo, never block it. When a Supabase call fails, the error is
 * logged once, the process switches to memory for the remainder of its life,
 * and the request completes. `storageMode()` reports which path is active so
 * the UI can say so rather than implying persistence that isn't happening.
 */

type Mode = "supabase" | "memory"

/** Flips to "memory" permanently if Supabase fails, so one outage doesn't
 *  produce a request-by-request mix of two stores. */
let degraded = false

export function storageMode(): Mode {
  return supabaseConfigured() && !degraded ? "supabase" : "memory"
}

/** True when Supabase is configured but a call failed and we fell back. */
export function storageDegraded(): boolean {
  return supabaseConfigured() && degraded
}

/**
 * Runs the Supabase implementation when available, falling back to memory.
 *
 * Both arms are passed as thunks rather than pre-computed, so the memory path
 * costs nothing when Supabase is healthy and vice versa.
 */
async function run<T>(
  remote: () => Promise<T>,
  local: () => T | Promise<T>
): Promise<T> {
  if (storageMode() === "memory") return local()
  try {
    return await remote()
  } catch (err) {
    degraded = true
    console.error(
      "[store] Supabase call failed — falling back to in-memory for this process.",
      err instanceof Error ? err.message : err
    )
    return local()
  }
}

// Re-exported unchanged: pure helpers with no backend of their own.
export const newId = memory.newId
export const now = memory.now
export const newTrackingId = memory.newTrackingId

// ---------------------------------------------------------------- departments

export function listDepartments(): Promise<Department[]> {
  return run(sb.listDepartments, memory.listDepartments)
}

export function getDepartment(id: string): Promise<Department | undefined> {
  return run(
    () => sb.getDepartment(id),
    () => memory.getDepartment(id)
  )
}

export function getDepartmentByToken(
  token: string
): Promise<Department | undefined> {
  return run(
    () => sb.getDepartmentByToken(token),
    () => memory.getDepartmentByToken(token)
  )
}

export function createDepartment(
  name: string,
  registrationToken: string
): Promise<Department> {
  return run(
    () => sb.createDepartment(name, registrationToken),
    () => memory.createDepartment(name, registrationToken)
  )
}

export function setSecurityLevel(
  id: string,
  level: SecurityLevel
): Promise<void> {
  return run(
    () => sb.setSecurityLevel(id, level),
    () => memory.setSecurityLevel(id, level)
  )
}

// ---------------------------------------------------------------- honeytokens

export function listHoneytokens(departmentId?: string): Promise<Honeytoken[]> {
  return run(
    () => sb.listHoneytokens(departmentId),
    () => memory.listHoneytokens(departmentId)
  )
}

export function getHoneytokenByTrackingId(
  trackingId: string
): Promise<Honeytoken | undefined> {
  return run(
    () => sb.getHoneytokenByTrackingId(trackingId),
    () => memory.getHoneytokenByTrackingId(trackingId)
  )
}

export function createHoneytoken(
  input: Omit<Honeytoken, "id" | "created_at" | "status"> &
    Partial<Pick<Honeytoken, "status">>
): Promise<Honeytoken> {
  return run(
    () => sb.createHoneytoken(input),
    () => memory.createHoneytoken(input)
  )
}

export function markHoneytokenTriggered(id: string): Promise<void> {
  return run(
    () => sb.markHoneytokenTriggered(id),
    () => memory.markHoneytokenTriggered(id)
  )
}

// --------------------------------------------------------------------- events

export function createEvent(
  input: Omit<Event, "id" | "timestamp">
): Promise<Event> {
  return run(
    () => sb.createEvent(input),
    () => memory.createEvent(input)
  )
}

export function listEvents(limit = 100): Promise<Event[]> {
  return run(
    () => sb.listEvents(limit),
    () => memory.listEvents(limit)
  )
}

export function countRecentUseEvents(
  sourceIp: string,
  windowMs: number
): Promise<number> {
  return run(
    () => sb.countRecentUseEvents(sourceIp, windowMs),
    () => memory.countRecentUseEvents(sourceIp, windowMs)
  )
}

// ------------------------------------------------------------------ incidents

export function findOpenIncident(
  sourceIp: string,
  departmentId: string
): Promise<Incident | undefined> {
  return run(
    () => sb.findOpenIncident(sourceIp, departmentId),
    () => memory.findOpenIncident(sourceIp, departmentId)
  )
}

export function createIncident(
  input: Omit<
    Incident,
    "id" | "created_at" | "updated_at" | "containment_latency_ms"
  > & { containment_latency_ms?: number | null }
): Promise<Incident> {
  return run(
    () => sb.createIncident(input),
    () => memory.createIncident(input)
  )
}

export function updateIncident(
  id: string,
  patch: Partial<Omit<Incident, "id" | "created_at">>
): Promise<Incident | undefined> {
  return run(
    () => sb.updateIncident(id, patch),
    () => memory.updateIncident(id, patch)
  )
}

export function listIncidents(departmentId?: string): Promise<Incident[]> {
  return run(
    () => sb.listIncidents(departmentId),
    () => memory.listIncidents(departmentId)
  )
}

export function attachEventToIncident(
  incidentId: string,
  eventId: string
): Promise<void> {
  return run(
    () => sb.attachEventToIncident(incidentId, eventId),
    () => memory.attachEventToIncident(incidentId, eventId)
  )
}

export function listIncidentEvents(incidentId: string): Promise<Event[]> {
  return run(
    () => sb.listIncidentEvents(incidentId),
    () => memory.listIncidentEvents(incidentId)
  )
}

// -------------------------------------------------------- containment actions

export function createContainmentAction(
  input: Omit<ContainmentActionRecord, "id" | "timestamp">
): Promise<ContainmentActionRecord> {
  return run(
    () => sb.createContainmentAction(input),
    () => memory.createContainmentAction(input)
  )
}

export function listContainmentActions(
  incidentId?: string
): Promise<ContainmentActionRecord[]> {
  return run(
    () => sb.listContainmentActions(incidentId),
    () => memory.listContainmentActions(incidentId)
  )
}

// ------------------------------------------------------------------- lifecycle

export function resetStore(): Promise<void> {
  return run(sb.resetStore, memory.resetStore)
}
